import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import { Inter, Roboto, Comfortaa } from "next/font/google";
import NavMenu from "@/components/NavMenu/NavMenu";
import AuthProvider from "./AuthProvider/AuthProvider";
import { ToastContainer } from "./tostify";
import "react-toastify/dist/ReactToastify.css";
import { ToogleProvider } from "@/store/context";

const inter = Comfortaa({
  weight: ["300", "400", "500", "700", "600"],
  style: ["normal"],
  subsets: ["latin"],
});

export const metadata = {
  title: "College",
  description: "Generated by Omkar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ToogleProvider>
            <AuthProvider>
              <Navbar />
              <div className="container">
                <NavMenu />
                {children}
                <ToastContainer />
              </div>
            </AuthProvider>
          </ToogleProvider>
      </body>
    </html>
  );
}
